apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}  ## IMPORTANT: Frontend Nginx depends on this exact name
  labels:
    app: {{ .Release.Name }}
    tier: backend   
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }} # Service Port
      targetPort: {{ .Values.service.targetPort }} # Container Port
      nodePort: {{ .Values.service.nodePort }} # NodePort for external access, add this during deployment through $(cd ../terraform && echo var.service_node_port | terraform console)
      protocol: TCP